### ISSUE TITLE
Can't style the relative number span element

### ISSUE THREAD

**Issue by akonwi** [justmoon/relative-numbers#29]
I'm creating a theme and before atom 1.13, I had some styling to change the color of the number on the current line. Once atom 1.13 came out, I noticed the styling was buggy and it was probably because atom removed the pseudo selectors api, so I disabled relative-numbers.

Today, I re-enabled the package and updated it and now the style rules of my theme aren't applied.

Here's the style block:

``` less
.relative.current-line {
  color: @white;
}
```

Am I missing something? I've also used the same selector that the dev tools is showing me for the block that declares the `color: #2196f3`, but that doesn't work either.

**Comment by justmoon** [comment]
Have you tried

``` css
atom-text-editor.editor .relative.current-line {
  color: purple
}
```

as suggested in the README?

**Comment by akonwi** [comment]
Yea I've tried that to no avail. Even in my local stylesheet that doesn't work. 

What I eventually figured out was that the selector `.relative.current-line` was not getting found. I could use it in the dev tools and it would find the element but from my stylesheets there was nothing. What I've done is replace the class selector with `span` and it works now.

More specifically, it looks like this:

``` less
atom-text-editor {
  .gutter {
    .line-number {
      &.cursor-line {
        span {
          color: white
        }
      }
    }
  }
}
```
